### PR TITLE
✨Add an option to recover panic for controller reconcile

### LINKED ISSUE #797: Reconciler panics should not crash the manager
Currently, an unhandled panic in a reconciler will not be recovered from, and will likely cause the manager binary to crash. This is a problem, since a panic might be triggered by a single resource in an unexpected state, so that one bad resource could prevent all other resources from being processed. Since Kubernetes is likely to restart the manager pod after a crash, this can also cause the manager to DOS the Kubernetes API server as it continually restarts.

In my project, I wrote this utility function:

```go
func MakeSafe(r reconcile.Reconciler) reconcile.Reconciler {
	return safeReconciler{impl: r}
}

type safeReconciler struct {
	impl reconcile.Reconciler
}

func (r safeReconciler) Reconcile(request reconcile.Request) (result reconcile.Result, err error) {
	defer func() {
		if r := recover(); r != nil {
			result = reconcile.Result{}
			err = fmt.Errorf("panic: %v [recovered]\n\n%s", r, debug.Stack())
		}
	}()
	return r.impl.Reconcile(request)
}
```

Every time I pass a reconciler to `Complete`, I wrap it with this. It ensures that any panics raised by the reconciler are converted to normal errors.

### PR DESCRIPTION
**Pull request by FillZpp**
Signed-off-by: FillZpp <FillZpp.pub@gmail.com>

Add an option to recover panic for controller reconcile. It ensures that any panics raised by controller reconciler are converted to normal errors.

fixes #797

### CODE REVIEW

File: pkg/internal/controller/controller.go [hunk 1]
```diff
@@ -321,6 +322,15 @@ func (c *Controller) reconcileHandler(ctx context.Context, obj interface{}) {
 	}
 }
 
+func (c *Controller) doReconcile(ctx context.Context, req reconcile.Request) (_ reconcile.Result, err error) {
+	defer func() {
```
Comment (alvaroaleman) [inline pkg/internal/controller/controller.go:326]: This should be optional and opt-in, similiar to what upstream does: https://github.com/kubernetes/apimachinery/blob/f916759cb6b8547418dc7708876ecab5c1961448/pkg/util/runtime/runtime.go#L29

Also, please add tests for this.

Comment (FillZpp) [reply pkg/internal/controller/controller.go]: Okay. I have added tests and changed all `recover()` to `utilruntime.HandleCrash()`, so that developers can set it via `utilruntime. ReallyCrash`.

File: pkg/internal/controller/controller.go [hunk 2]
```diff
@@ -95,7 +95,10 @@ type watchDescription struct {
 }
 
 // Reconcile implements reconcile.Reconciler.
-func (c *Controller) Reconcile(ctx context.Context, req reconcile.Request) (reconcile.Result, error) {
+func (c *Controller) Reconcile(ctx context.Context, req reconcile.Request) (_ reconcile.Result, err error) {
```
Comment (alvaroaleman) [inline pkg/internal/controller/controller.go:98]: Sorry, what I meant by the other comment was:
1. Please add an option to `Controller` to make this configurable (i.E. `RecoverPanic bool`)
2. Make the handling here conditional (i.E. `if c.RecoverPanic { defer recover() }`)
3. Expose the option in `pkg/controller.Options`


The reason for favoring that over the current approach is that with the current approach we require ppl to read internal packages to understand how they can get panics recovered, which is not good UX.

Sorry for being unclear about this before.

Comment (FillZpp) [reply pkg/internal/controller/controller.go:98]: Understand, I will fix it. So what do you think of webhook handler? Should its panic default to be recovered or another option field to configure it?

Comment (alvaroaleman) [reply pkg/internal/controller/controller.go:98]: It should also have an option to set this up and by default panic

Comment (FillZpp) [reply pkg/internal/controller/controller.go:101]: Updated. It is hard to add the option for webhook. Maybe we can firstly add an option for controller reconcile.

File: pkg/internal/controller/controller.go [hunk 3]
```diff
@@ -95,7 +98,17 @@ type watchDescription struct {
...
+	if c.RecoverPanic {
+		defer func() {
+			if r := recover(); r != nil {
+				for _, fn := range utilruntime.PanicHandlers {
+					fn(r)
+				}
+				err = fmt.Errorf("panic: %v [recovered]", r)
```
Comment (alvaroaleman) [inline pkg/internal/controller/controller.go:108]: Could we add the stack here, otherwise this is almost impossible to debug? From `runtime/debug.Stack()`

File: pkg/internal/controller/controller_test.go [hunk 4]
```diff
@@ -88,6 +88,41 @@ var _ = Describe("controller", func() {
...
+			defer func() {
+				Expect(recover()).ShouldNot(BeNil())
+			}()
+			ctrl.Do = reconcile.Func(func(context.Context, reconcile.Request) (reconcile.Result, error) {
+				var res *reconcile.Result
+				return *res, nil
+			})
+			_, _ = ctrl.Reconcile(ctx,
+				reconcile.Request{NamespacedName: types.NamespacedName{Namespace: "foo", Name: "bar"}})
+			By("this should not be called")
```
Comment (alvaroaleman) [inline pkg/internal/controller/controller_test.go:105]: Nit: Is this needed? The `defer` should make the test fail if it doesn't work or not?

File: pkg/internal/controller/controller.go (hunk 3 above)
Comment (FillZpp) [reply pkg/internal/controller/controller.go:108]: Maybe the `utilruntime.PanicHandlers` above can print the stack of panic more properly 
 https://github.com/kubernetes/apimachinery/blob/f916759cb6b8547418dc7708876ecab5c1961448/pkg/util/runtime/runtime.go#L61

File: pkg/internal/controller/controller_test.go (hunk 4 above)
Comment (FillZpp) [reply pkg/internal/controller/controller_test.go]: Have removed this.

**Review by alvaroaleman — APPROVED** [review]
Thank you!
