### PR TITLE
:bug: Update typed Applyconfigurations with server response

### LINKED ISSUE #3474: Apply using typed apply configurations doesn't deserialize the response into the passed object
The client-go result requires a runtime.Object to decode into: https://github.com/kubernetes/kubernetes/blob/dfbe79674a33c47c1f0fd7b75882314f6db5e136/staging/src/k8s.io/client-go/rest/request.go#L1449

Because of this, the controller-runtime typed apply wraps the passed applyconfiguration with something that implements runtime.Object and embedds an interface for the applyconfiguration: https://github.com/kubernetes-sigs/controller-runtime/blob/105baa6284da3d3ca5dc23b3fe1dd30df7ea3df7/pkg/client/typed_client.go#L159 https://github.com/kubernetes-sigs/controller-runtime/blob/105baa6284da3d3ca5dc23b3fe1dd30df7ea3df7/pkg/client/applyconfigurations.go#L60-L62

The json unmarshaller however doesn't inline interfaces, only embedded structs. As a result, only hypothetical fields under an `ApplyConfiguration` key would be deserialized into the applyconfiguration and hence we never update the passed applyconfiguration. 

Deserialization of the result works fine in the case of unstructured.

/kind bug
/assign

### PR DESCRIPTION
**Pull request by alvaroaleman**
Prior to this, we would never update a typed applyconfiguration with the response from the server, this change fixes that.

Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/3474

### CODE REVIEW

**Comment by alvaroaleman** [comment]
One question is if we should backport this, the problem with that is that it may break existing code, since the response contains a resource version, so when re-using an object to do multiple requests that would have previously worked but won't anymore after this

**Review by dongjiang1989 — APPROVED** [review]
LGTM

**Comment by sbueringer** [comment]
/hold

We should discuss this a bit

File: pkg/client/typed_client.go [hunk 1]
```diff
@@ -146,17 +147,18 @@ func (c *typedClient) Apply(ctx context.Context, obj runtime.ApplyConfiguration,
...
-		// that is not implemented by the ApplyConfigurations. The generated clients
-		// don't have this problem because they deserialize into the api type, not the
-		// apply configuration: https://github.com/kubernetes/kubernetes/blob/22f5e01a37c0bc6a5f494dec14dd4e3688ee1d55/staging/src/k8s.io/client-go/gentype/type.go#L296-L317
-		Into(runtimeObjectFromApplyConfiguration(obj))
+		Raw()
+	if err != nil {
+		return err
+	}
+
+	return json.Unmarshal(body, obj)
```
Comment (sbueringer) [inline pkg/client/typed_client.go:167]: Do we have to do some sort of zeroing on the obj?

File: pkg/client/client_test.go [hunk 2]
```diff
@@ -1015,6 +1016,7 @@ U5wwSivyi7vmegHKmblOzNVKA5qPO8zWzqBC
 
 				err = cl.Apply(ctx, obj, &client.ApplyOptions{FieldManager: "test-manager"})
 				Expect(err).NotTo(HaveOccurred())
+				Expect(obj.ResourceVersion).NotTo(BeNil())
```
Comment (sbueringer) [inline pkg/client/client_test.go:1019]: Can we add something similar for subresource Apply?

**Comment by sbueringer** [comment]
> We should discuss this a bit

Added my take on the issue

File: pkg/client/client_test.go (hunk 2 above)
Comment (alvaroaleman) [reply pkg/client/client_test.go:1019]: Done

File: pkg/client/typed_client.go (hunk 1 above)
Comment (alvaroaleman) [reply pkg/client/typed_client.go:167]: Arguably yes but we don't do that for other requests either, so I'd prefer if we either do it consistently for all of them or for none

**Comment by matheuscscp** [comment]
Hey @sbueringer, sorry for the ping, looks like this is the last unresolved item for v0.24.0 according to the tracking issue. Can you please review? :pray:

File: pkg/client/typed_client.go [hunk 3]
```diff
@@ -146,17 +147,24 @@ func (c *typedClient) Apply(ctx context.Context, obj runtime.ApplyConfiguration,
...
-		// don't have this problem because they deserialize into the api type, not the
-		// apply configuration: https://github.com/kubernetes/kubernetes/blob/22f5e01a37c0bc6a5f494dec14dd4e3688ee1d55/staging/src/k8s.io/client-go/gentype/type.go#L296-L317
-		Into(runtimeObjectFromApplyConfiguration(obj))
+		ContentType(&contentType).
+		Raw()
+	if err != nil {
+		return err
+	}
+
+	if contentType != "application/json" {
```
Comment (sbueringer) [inline pkg/client/typed_client.go:163]: Do we also want this safeguard in ApplySubResource?

**Review by sbueringer — COMMENTED** [review]
One nit

File: pkg/client/typed_client.go (hunk 3 above)
Comment (alvaroaleman) [reply pkg/client/typed_client.go:163]: Added it there

**Comment by sbueringer** [comment]
Thank you very much!

/lgtm
/approve
/hold cancel
