### PR TITLE
🌱 verify go modules are in sync with upstream k/k

### LINKED ISSUE #2769: Add a validation script to verify go.mod is in sync with k/k
xref: https://github.com/kubernetes-sigs/controller-runtime/pull/2765#issuecomment-2048566997

Idea is to verify on PRs (pre-submit) that our go.mod file doesn't go out of sync with Kubernetes (with the k/k version we use). The goal is to avoid issues like this: https://github.com/kubernetes-sigs/controller-runtime/issues/2742 which can easily sneak in when we just merge dependabot PRs.

(we might want to consider exceptions for a few dependencies like ginkgo / gomega but that is TBD)

### PR DESCRIPTION
**Pull request by alexandremahdhaoui**
This PR should address the following issue #2769.

## Changes

- add `gomodcheck`:
  - Parse and compares k/k direct dependencies to controller-runtime's direct deps.
  - If any version diffs is found, returns a payload describing the diffs and exit 1.
  - The user may exclude packages by passing them as arguments.
- add `gomodcheck` to the `verify-modules` make target.

Fixes #2769

### CODE REVIEW

**Comment by alexandremahdhaoui** [comment]
Here is a list of currently out of sync dependencies:

```json
{
  "outOfSyncModules": [
    {
      "name": "github.com/prometheus/client_golang",
      "version": "v1.17.0",
      "upstreamVersion": "v1.16.0"
    },
    {
      "name": "github.com/prometheus/client_model",
      "version": "v0.4.1-0.20230718164431-9a2bf3000d16",
      "upstreamVersion": "v0.4.0"
    },
    {
      "name": "golang.org/x/sys",
      "version": "v0.19.0",
      "upstreamVersion": "v0.18.0"
    },
    {
      "name": "go.uber.org/zap",
      "version": "v1.27.0",
      "upstreamVersion": "v1.26.0"
    },
    {
      "name": "sigs.k8s.io/yaml",
      "version": "v1.4.0",
      "upstreamVersion": "v1.3.0"
    }
  ]
}
```

**Comment by sbueringer** [comment]
Looks like we can downgrade go.uber.org/zap, golang.org/x/sys, sigs.k8s.io/yaml

I assume this is also what we would want to do to play it absolutely safe (consumers of CR can still bump to higher versions if they are sure).

Not sure what is going on with the prometheus/client_* libs. go mod tidy automatically bumps them. Have to take a closer look

(cc @vincepri @alvaroaleman)

File: tools/cmd/gomodcheck/main.go [hunk 1]
```diff
@@ -0,0 +1,119 @@
+package main
```
Comment (sbueringer) [inline tools/cmd/gomodcheck/main.go:1]: I think I would move this to hack/tools/gomodcheck
(as it's only meant for us and not for other folks writing controllers)

**Comment by sbueringer** [comment]
PR to fix the current open findings: https://github.com/kubernetes-sigs/controller-runtime/pull/2776

File: tools/cmd/gomodcheck/main.go (hunk 1 above)
Comment (vincepri) [reply tools/cmd/gomodcheck/main.go:1]: Could we instead check the output from `go mod list` to achieve the same?

Comment (vincepri) [reply tools/cmd/gomodcheck/main.go:1]: example: `go mod graph | grep "^k8s.io/apiserver"` returns:

```
k8s.io/apiserver@v0.30.0-rc.1 github.com/coreos/go-oidc@v2.2.1+incompatible
k8s.io/apiserver@v0.30.0-rc.1 github.com/coreos/go-systemd/v22@v22.5.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/emicklei/go-restful/v3@v3.11.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/evanphx/json-patch@v4.12.0+incompatible
k8s.io/apiserver@v0.30.0-rc.1 github.com/fsnotify/fsnotify@v1.7.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/gogo/protobuf@v1.3.2
k8s.io/apiserver@v0.30.0-rc.1 github.com/google/cel-go@v0.17.8
k8s.io/apiserver@v0.30.0-rc.1 github.com/google/gnostic-models@v0.6.8
k8s.io/apiserver@v0.30.0-rc.1 github.com/google/go-cmp@v0.6.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/google/gofuzz@v1.2.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/google/uuid@v1.3.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/gorilla/websocket@v1.5.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/munnerz/goautoneg@v0.0.0-20191010083416-a7dc8b61c822
k8s.io/apiserver@v0.30.0-rc.1 github.com/mxk/go-flowrate@v0.0.0-20140419014527-cca7078d478f
k8s.io/apiserver@v0.30.0-rc.1 github.com/spf13/pflag@v1.0.5
k8s.io/apiserver@v0.30.0-rc.1 github.com/stretchr/testify@v1.8.4
k8s.io/apiserver@v0.30.0-rc.1 go.etcd.io/etcd/api/v3@v3.5.10
k8s.io/apiserver@v0.30.0-rc.1 go.etcd.io/etcd/client/pkg/v3@v3.5.10
k8s.io/apiserver@v0.30.0-rc.1 go.etcd.io/etcd/client/v3@v3.5.10
k8s.io/apiserver@v0.30.0-rc.1 go.etcd.io/etcd/server/v3@v3.5.10
k8s.io/apiserver@v0.30.0-rc.1 go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.42.0
k8s.io/apiserver@v0.30.0-rc.1 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.44.0
k8s.io/apiserver@v0.30.0-rc.1 go.opentelemetry.io/otel@v1.19.0
k8s.io/apiserver@v0.30.0-rc.1 go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc@v1.19.0
k8s.io/apiserver@v0.30.0-rc.1 go.opentelemetry.io/otel/sdk@v1.19.0
k8s.io/apiserver@v0.30.0-rc.1 go.opentelemetry.io/otel/trace@v1.19.0
k8s.io/apiserver@v0.30.0-rc.1 go.uber.org/zap@v1.26.0
k8s.io/apiserver@v0.30.0-rc.1 golang.org/x/crypto@v0.19.0
k8s.io/apiserver@v0.30.0-rc.1 golang.org/x/net@v0.21.0
k8s.io/apiserver@v0.30.0-rc.1 golang.org/x/sync@v0.6.0
k8s.io/apiserver@v0.30.0-rc.1 golang.org/x/sys@v0.17.0
k8s.io/apiserver@v0.30.0-rc.1 golang.org/x/time@v0.3.0
k8s.io/apiserver@v0.30.0-rc.1 google.golang.org/genproto/googleapis/api@v0.0.0-20230726155614-23370e0ffb3e
k8s.io/apiserver@v0.30.0-rc.1 google.golang.org/grpc@v1.58.3
k8s.io/apiserver@v0.30.0-rc.1 google.golang.org/protobuf@v1.33.0
k8s.io/apiserver@v0.30.0-rc.1 gopkg.in/natefinch/lumberjack.v2@v2.2.1
k8s.io/apiserver@v0.30.0-rc.1 gopkg.in/square/go-jose.v2@v2.6.0
k8s.io/apiserver@v0.30.0-rc.1 k8s.io/api@v0.30.0-rc.1
k8s.io/apiserver@v0.30.0-rc.1 k8s.io/apimachinery@v0.30.0-rc.1
k8s.io/apiserver@v0.30.0-rc.1 k8s.io/client-go@v0.30.0-rc.1
k8s.io/apiserver@v0.30.0-rc.1 k8s.io/component-base@v0.30.0-rc.1
k8s.io/apiserver@v0.30.0-rc.1 k8s.io/klog/v2@v2.120.1
k8s.io/apiserver@v0.30.0-rc.1 k8s.io/kms@v0.30.0-rc.1
k8s.io/apiserver@v0.30.0-rc.1 k8s.io/kube-openapi@v0.0.0-20240228011516-70dd3763d340
k8s.io/apiserver@v0.30.0-rc.1 k8s.io/utils@v0.0.0-20230726121419-3b25d923346b
k8s.io/apiserver@v0.30.0-rc.1 sigs.k8s.io/apiserver-network-proxy/konnectivity-client@v0.29.0
k8s.io/apiserver@v0.30.0-rc.1 sigs.k8s.io/json@v0.0.0-20221116044647-bc3834ca7abd
k8s.io/apiserver@v0.30.0-rc.1 sigs.k8s.io/structured-merge-diff/v4@v4.4.1
k8s.io/apiserver@v0.30.0-rc.1 sigs.k8s.io/yaml@v1.3.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/NYTimes/gziphandler@v1.1.1
k8s.io/apiserver@v0.30.0-rc.1 github.com/antlr/antlr4/runtime/Go/antlr/v4@v4.0.0-20230305170008-8188dc5388df
k8s.io/apiserver@v0.30.0-rc.1 github.com/asaskevich/govalidator@v0.0.0-20190424111038-f61b66f89f4a
k8s.io/apiserver@v0.30.0-rc.1 github.com/beorn7/perks@v1.0.1
k8s.io/apiserver@v0.30.0-rc.1 github.com/blang/semver/v4@v4.0.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/cenkalti/backoff/v4@v4.2.1
k8s.io/apiserver@v0.30.0-rc.1 github.com/cespare/xxhash/v2@v2.2.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/coreos/go-semver@v0.3.1
k8s.io/apiserver@v0.30.0-rc.1 github.com/davecgh/go-spew@v1.1.1
k8s.io/apiserver@v0.30.0-rc.1 github.com/dustin/go-humanize@v1.0.1
k8s.io/apiserver@v0.30.0-rc.1 github.com/felixge/httpsnoop@v1.0.3
k8s.io/apiserver@v0.30.0-rc.1 github.com/go-logr/logr@v1.4.1
k8s.io/apiserver@v0.30.0-rc.1 github.com/go-logr/stdr@v1.2.2
k8s.io/apiserver@v0.30.0-rc.1 github.com/go-openapi/jsonpointer@v0.19.6
k8s.io/apiserver@v0.30.0-rc.1 github.com/go-openapi/jsonreference@v0.20.2
k8s.io/apiserver@v0.30.0-rc.1 github.com/go-openapi/swag@v0.22.3
k8s.io/apiserver@v0.30.0-rc.1 github.com/golang-jwt/jwt/v4@v4.5.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/golang/groupcache@v0.0.0-20210331224755-41bb18bfe9da
k8s.io/apiserver@v0.30.0-rc.1 github.com/golang/protobuf@v1.5.4
k8s.io/apiserver@v0.30.0-rc.1 github.com/google/btree@v1.0.1
k8s.io/apiserver@v0.30.0-rc.1 github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/grpc-ecosystem/grpc-gateway@v1.16.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/grpc-ecosystem/grpc-gateway/v2@v2.16.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/imdario/mergo@v0.3.6
k8s.io/apiserver@v0.30.0-rc.1 github.com/inconshreveable/mousetrap@v1.1.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/jonboulle/clockwork@v0.2.2
k8s.io/apiserver@v0.30.0-rc.1 github.com/josharian/intern@v1.0.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/json-iterator/go@v1.1.12
k8s.io/apiserver@v0.30.0-rc.1 github.com/mailru/easyjson@v0.7.7
k8s.io/apiserver@v0.30.0-rc.1 github.com/matttproud/golang_protobuf_extensions@v1.0.4
k8s.io/apiserver@v0.30.0-rc.1 github.com/moby/spdystream@v0.2.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/modern-go/concurrent@v0.0.0-20180306012644-bacd9c7ef1dd
k8s.io/apiserver@v0.30.0-rc.1 github.com/modern-go/reflect2@v1.0.2
k8s.io/apiserver@v0.30.0-rc.1 github.com/pkg/errors@v0.9.1
k8s.io/apiserver@v0.30.0-rc.1 github.com/pmezard/go-difflib@v1.0.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/pquerna/cachecontrol@v0.1.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/prometheus/client_golang@v1.16.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/prometheus/client_model@v0.4.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/prometheus/common@v0.44.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/prometheus/procfs@v0.10.1
k8s.io/apiserver@v0.30.0-rc.1 github.com/sirupsen/logrus@v1.9.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/soheilhy/cmux@v0.1.5
k8s.io/apiserver@v0.30.0-rc.1 github.com/spf13/cobra@v1.7.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/stoewer/go-strcase@v1.2.0
k8s.io/apiserver@v0.30.0-rc.1 github.com/tmc/grpc-websocket-proxy@v0.0.0-20220101234140-673ab2c3ae75
k8s.io/apiserver@v0.30.0-rc.1 github.com/xiang90/probing@v0.0.0-20190116061207-43a291ad63a2
k8s.io/apiserver@v0.30.0-rc.1 go.etcd.io/bbolt@v1.3.8
k8s.io/apiserver@v0.30.0-rc.1 go.etcd.io/etcd/client/v2@v2.305.10
k8s.io/apiserver@v0.30.0-rc.1 go.etcd.io/etcd/pkg/v3@v3.5.10
k8s.io/apiserver@v0.30.0-rc.1 go.etcd.io/etcd/raft/v3@v3.5.10
k8s.io/apiserver@v0.30.0-rc.1 go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.19.0
k8s.io/apiserver@v0.30.0-rc.1 go.opentelemetry.io/otel/metric@v1.19.0
k8s.io/apiserver@v0.30.0-rc.1 go.opentelemetry.io/proto/otlp@v1.0.0
k8s.io/apiserver@v0.30.0-rc.1 go.uber.org/multierr@v1.11.0
k8s.io/apiserver@v0.30.0-rc.1 golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e
k8s.io/apiserver@v0.30.0-rc.1 golang.org/x/oauth2@v0.10.0
k8s.io/apiserver@v0.30.0-rc.1 golang.org/x/term@v0.17.0
k8s.io/apiserver@v0.30.0-rc.1 golang.org/x/text@v0.14.0
k8s.io/apiserver@v0.30.0-rc.1 google.golang.org/appengine@v1.6.7
k8s.io/apiserver@v0.30.0-rc.1 google.golang.org/genproto@v0.0.0-20230803162519-f966b187b2e5
k8s.io/apiserver@v0.30.0-rc.1 google.golang.org/genproto/googleapis/rpc@v0.0.0-20230822172742-b8732ec3820d
k8s.io/apiserver@v0.30.0-rc.1 gopkg.in/inf.v0@v0.9.1
k8s.io/apiserver@v0.30.0-rc.1 gopkg.in/yaml.v2@v2.4.0
k8s.io/apiserver@v0.30.0-rc.1 gopkg.in/yaml.v3@v3.0.1
k8s.io/apiserver@v0.30.0-rc.1 go@1.22.0
```

File: tools/cmd/gomodcheck/main.go [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+	"net/http"
+	"os"
+	"regexp"
+	"strings"
+
+	"sigs.k8s.io/controller-runtime/pkg/log/zap"
+)
+
+const (
+	kkModUrl = "https://raw.githubusercontent.com/kubernetes/kubernetes/master/go.mod"
```
[the remark this answers is not in the document]
Comment (alexandremahdhaoui) [reply tools/cmd/gomodcheck/main.go:16]: Thanks I'll use this.

File: tools/cmd/gomodcheck/main.go (hunk 1 above)
Comment (alexandremahdhaoui) [reply tools/cmd/gomodcheck/main.go:1]: It's a more elegant solution, I'll proceed with that change

File: tools/cmd/gomodcheck/main.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (alexandremahdhaoui) [reply tools/cmd/gomodcheck/main.go]: This should be fixed 75371f34d8dfba56541dccdc9d4710bb4d556c95.

File: tools/cmd/gomodcheck/main.go (hunk 1 above)
Comment (alexandremahdhaoui) [reply tools/cmd/gomodcheck/main.go]: @vincepri I made the tool able to verify modules onto any upstream using your suggestion.

**Comment by alexandremahdhaoui** [comment]
The modules listed below are also out of sync:

```json
{
  "outOfSyncModules": [
    {
      "name": "github.com/go-logr/logr",
      "version": "v1.4.1",
      "upstreams": [
        {
          "ref": "k8s.io/utils",
          "version": "v1.2.0"
        }
      ]
    },
    {
      "name": "k8s.io/klog/v2",
      "version": "v2.120.1",
      "upstreams": [
        {
          "ref": "k8s.io/utils",
          "version": "v2.80.1"
        }
      ]
    }
  ]
}
```

**Comment by sbueringer** [comment]
Did I understand this correctly that we are now finding inconsistencies between our dependencies?

E.g. 
* k8s.io/utils
  * we use: v2.120.1
  * k/k uses: v2.120.1
  * k8s.io/utils v0.0.0-20230726121419-3b25d923346b uses v2.80.1

Given that we are using the same k8s.io/utils as k/k go.mod I don't think it's fixable for us to ensure all of these dependencies sync up.

I think we have to restrict the dependencies we go through (e.g. focusing on that some "core/main" k/k modules are in sync with us, like k8s.io/client-go.

**Comment by sbueringer** [comment]
@vincepri I think this is a consequence of now looking at the go mod graph instead of looking at the k/k go.mod file. WDYT? (I would suggest to just compare dependencies between CR and a few "main/core" go modules of k/k)

**Comment by amahdhaoui-ionos** [comment]
@sbueringer The fields names in the output are confusing. 

I'll explain the output. We have 2 out of sync modules, namely:
- `github.com/go-logr/logr`
    - local: `v1.4.1`
    - upstream: `v1.2.0`
- `k8s.io/klog/v2`
    - local: `v2.120.1`
    - upstream: `v2.80.1`

However, because we verify multiple upstream packages if `upstreamVersion` is a string we may overwrite and silence findings made from other upstream. Therefore too avoid inconsistencies and make it explicit, along the upstream version of the module, we specify which upstream specifies the module in which version. Hence, the `"ref": "k8s.io/utils"` fields.

I agree it's very convoluted. Do you have any suggestions to better name those output fields.

**Comment by alexandremahdhaoui** [comment]
@sbueringer The fields names in the output are confusing. 

I'll explain the output. We have 2 out of sync modules, namely:
- `github.com/go-logr/logr`
    - local: `v1.4.1`
    - upstream: `v1.2.0`
- `k8s.io/klog/v2`
    - local: `v2.120.1`
    - upstream: `v2.80.1`

However, because we verify multiple upstream packages if `upstreamVersion` is a string we may overwrite and silence findings made from other upstream. Therefore to avoid inconsistencies and make it explicit, we specify the upstream and the version of the affected module. Hence, the `"ref": "k8s.io/utils"` fields.

I agree it's very convoluted. Do you have any suggestions to better name those output fields.

**Comment by alexandremahdhaoui** [comment]
NB: I was wondering if it can be considered okay if I create a personal repo to write an enhanced version of `gomodcheck` and release it there? The tool can be useful and re-used for other projects.

**Comment by sbueringer** [comment]
> NB: I was wondering if it can be considered okay if I create a personal repo to write an enhanced version of `gomodcheck` and release it there? The tool can be useful and re-used for other projects.

Definitely okay to do that, but we're very hesitant to add dependencies to personal repos. So we would continue to use our local version I think

**Comment by sbueringer** [comment]
@alexandremahdhaoui I tried to use it on top of #2786 and I'm getting some strange results:

```
 make verify-modules
go mod tidy
cd hack/tools; go mod tidy
cd /Users/buringerst/code/src/sigs.k8s.io/controller-runtime/tools/setup-envtest; go mod tidy
cd /Users/buringerst/code/src/sigs.k8s.io/controller-runtime/examples/scratch-env; go mod tidy
/Users/buringerst/code/src/sigs.k8s.io/controller-runtime/hack/tools/bin/gomodcheck /Users/buringerst/code/src/sigs.k8s.io/controller-runtime/hack/.gomodcheck.yaml
{
  "outOfSyncModules": [
    {
      "name": "k8s.io/api",
      "version": "v0.30.0",
      "upstreamVersion": "v0.0.0"
    },
    {
      "name": "k8s.io/client-go",
      "version": "v0.30.0",
      "upstreamVersion": "v0.0.0"
    },
    {
      "name": "github.com/onsi/gomega",
      "version": "v1.32.0",
      "upstreamVersion": "v1.31.0"
    },
    {
      "name": "k8s.io/component-base",
      "version": "v0.30.0",
      "upstreamVersion": "v0.0.0"
    },
    {
      "name": "github.com/onsi/ginkgo/v2",
      "version": "v2.17.1",
      "upstreamVersion": "v2.15.0"
    },
    {
      "name": "k8s.io/apiextensions-apiserver",
      "version": "v0.30.0",
      "upstreamVersion": "v0.0.0"
    },
    {
      "name": "k8s.io/apimachinery",
      "version": "v0.30.0",
      "upstreamVersion": "v0.0.0"
    },
    {
      "name": "k8s.io/apiserver",
      "version": "v0.30.0",
      "upstreamVersion": "v0.0.0"
    }
  ]
}
make: *** [verify-modules] Error 1
```

**Comment by alexandremahdhaoui** [comment]
@sbueringer it looks like you've cherry-picked an old commit of this branch.
NB: I've rebased onto main and it

File: Makefile [hunk 3]
```diff
@@ -92,6 +92,12 @@ GOLANGCI_LINT_PKG := github.com/golangci/golangci-lint/cmd/golangci-lint
 $(GOLANGCI_LINT): # Build golangci-lint from tools folder.
 	GOBIN=$(TOOLS_BIN_DIR) $(GO_INSTALL) $(GOLANGCI_LINT_PKG) $(GOLANGCI_LINT_BIN) $(GOLANGCI_LINT_VER)
 
+GO_MOD_CHECK_DIR := $(abspath ./hack/tools/cmd/gomodcheck)
+GO_MOD_CHECK := $(abspath $(TOOLS_BIN_DIR)/gomodcheck)
+GO_MOD_CHECK_IGNORE := $(abspath ./hack/.gomodcheck.yaml)
+$(GO_MOD_CHECK): # Build gomodcheck
```
Comment (sbueringer) [inline Makefile:98]:
```suggestion
.PHONY: $(GO_MOD_CHECK)
$(GO_MOD_CHECK): # Build gomodcheck
```
Let's add this to force the build of the binary. Otherwise it doesn't get rebuild when the code of the binary changes (which is why I got wrong results when testing it locally)

File: hack/tools/cmd/gomodcheck/main.go [hunk 4]
```diff
@@ -0,0 +1,203 @@
...
+}
+
+var (
+	cleanMods     = regexp.MustCompile(`\t| *//.*`)
+	modDelimStart = regexp.MustCompile(`^require.*`)
+	modDelimEnd   = ")"
+)
+
+func parseModFile() (map[string]string, error) {
+	b, err := os.ReadFile(modFile)
```
Comment (sbueringer) [inline hack/tools/cmd/gomodcheck/main.go:130]: WDYT about using this package to parse the mod file? (https://pkg.go.dev/golang.org/x/mod/modfile)

(not sure how easy it is to use)

Just want to avoid that this code here breaks when they change the format in some way

File: hack/tools/cmd/gomodcheck/main.go [hunk 5]
```diff
@@ -0,0 +1,203 @@
...
+}
+
+func getUpstreamModGraph(upstreamRefs []string) (map[string]map[string]string, error) {
+	b, err := exec.Command("go", "mod", "graph").Output()
+	if err != nil {
+		return nil, err
+	}
+
+	graph := string(b)
+	o1Refs := make(map[string]bool)
```
Comment (sbueringer) [inline hack/tools/cmd/gomodcheck/main.go:165]: What does o1 stand for?

File: hack/tools/cmd/gomodcheck/main.go [hunk 6]
```diff
@@ -0,0 +1,203 @@
...
+			kv := strings.SplitN(strings.SplitN(line, " ", 2)[1], "@", 2)
+			name := kv[0]
+			version := kv[1]
+
+			if m, ok := modToVersionToUpstreamRef[kv[0]]; ok {
+				m[version] = upstreamRef
+			} else {
+				versionToRef := map[string]string{version: upstreamRef}
+				modToVersionToUpstreamRef[name] = versionToRef
+			}
```
Comment (sbueringer) [inline hack/tools/cmd/gomodcheck/main.go:185]:
```suggestion
			if _, ok := modToVersionToUpstreamRef[name]; !ok {
				modToVersionToUpstreamRef[name] = map[string]string{}
			}
			modToVersionToUpstreamRef[name][version] = upstreamRef
```
nit

**Review by sbueringer — COMMENTED** [review]
Overall looks good. Just a few smaller findings

File: hack/tools/cmd/gomodcheck/main.go (hunk 5 above)
Comment (alexandremahdhaoui) [reply hack/tools/cmd/gomodcheck/main.go:165]: I think the suggestion below clarifies the intent. If it makes sense to you, I'll update the code accordingly.

```suggestion
        // foundRef holds refs to user specified upstreamRefs that were found in the go.mod file.
        // gomodcheck exits with an error if user specifies unused upstreamRefs.
	foundRef := make(map[string]any)
```

File: hack/tools/cmd/gomodcheck/main.go (hunk 6 above)
Comment (alexandremahdhaoui) [reply hack/tools/cmd/gomodcheck/main.go:185]: Thank you, that's way better. If you wish to update your suggestion with `make()` it would be even better.

```suggestion
			if _, ok := modToVersionToUpstreamRef[name]; !ok {
				modToVersionToUpstreamRef[name] = make(map[string]string)
			}
			modToVersionToUpstreamRef[name][version] = upstreamRef
```

File: hack/tools/cmd/gomodcheck/main.go (hunk 4 above)
Comment (alexandremahdhaoui) [reply hack/tools/cmd/gomodcheck/main.go:130]: That is an elegant alternative. I'll use it instead, thanks.

NB: I was initially looking into `modload.LoadModGraph` but is an internal package: https://github.com/golang/go/blob/master/src/cmd/go/internal/modload/buildlist.go#L565

File: hack/.gomodcheck.yaml [hunk 7]
```diff
@@ -0,0 +1,14 @@
+upstreamRefs:
```
[the remark this answers is not in the document]
Comment (alexandremahdhaoui) [reply hack/.gomodcheck.yaml:1]: Makes sense, I'll move it there.

File: hack/tools/cmd/gomodcheck/main.go (hunk 5 above)
Comment (sbueringer) [reply hack/tools/cmd/gomodcheck/main.go:165]: Yup, perfect. Thx!

File: hack/tools/cmd/gomodcheck/main.go (hunk 6 above)
Comment (sbueringer) [reply hack/tools/cmd/gomodcheck/main.go:185]: Sounds good!

Comment (alexandremahdhaoui) [reply hack/tools/cmd/gomodcheck/main.go]: Should be fixed!

File: hack/tools/cmd/gomodcheck/main.go (hunk 5 above)
Comment (alexandremahdhaoui) [reply hack/tools/cmd/gomodcheck/main.go]: Fixed in 6449beb3.

File: hack/tools/cmd/gomodcheck/main.go (hunk 4 above)
Comment (alexandremahdhaoui) [reply hack/tools/cmd/gomodcheck/main.go:124]: Fixed in 6449beb3.

Comment (sbueringer) [reply hack/tools/cmd/gomodcheck/main.go:128]: Nice!

**Comment by sbueringer** [comment]
Very nice. Thank you!

/lgtm
/approve

**Comment by sbueringer** [comment]
> > NB: I was wondering if it can be considered okay if I create a personal repo to write an enhanced version of `gomodcheck` and release it there? The tool can be useful and re-used for other projects.
> 
> Definitely okay to do that, but we're very hesitant to add dependencies to personal repos. So we would continue to use our local version I think

@alexandremahdhaoui Just talked about this with a colleague and he meant it would be great if this would become a separate linter and maybe eventually other folks would be able to use it through golangci-lint

**Comment by randomvariable** [comment]
It's me, I'm the colleague. I think even a subdirectory under https://github.com/kubernetes/release would be fine. Seems to have broad applicability across SIG groups.

**Comment by alexandremahdhaoui** [comment]
Hi folks - @sbueringer  @randomvariable , I missed your messages earlier. I can follow it up if it's still relevant today.

**Comment by sbueringer** [comment]
I think it is
