### PR TITLE
⚠ fix: Stop accumulating lists in multi-namespace cache implementation

### LINKED ISSUE #3194: Bug: multi_namespace_cache List() method accumulates results across subsequent calls
## Problem

When using the controller-runtime cache with DefaultNamespaces configured (via `ctrl.Options.NewCache`), the `List()` method causes results to accumulate. Each subsequent call to `List()` includes the results from previous calls, causing the result set to continuously grow.

## Steps to Reproduce

1. Create a cache with DefaultNamespaces configuration:

```go
mgr, err := ctrl.NewManager(cfg, ctrl.Options{
    NewCache: func(config *rest.Config, opts cache.Options) (cache.Cache, error) {
        opts.DefaultNamespaces = map[string]cache.Config{
            "default": {},
        }
        return cache.New(config, opts)
    },
})

```

2. Repeatedly call the List() method in a loop:

```go
pods := &corev1.PodList{}
ctx, cancel := context.WithTimeout(ctx, 1*time.Minute)
defer cancel()
for {
    select {
    case <-ctx.Done():
        t.Fatal("timeout")
    default:
        err := c.List(ctx, pods)
        // Examine pods.Items length - it grows with each call
    }
}
```

Each call to List() should return the current state of resources, not accumulate previous results. The result set should be reset and then populated with the current state of resources.

- version: `v0.20.4`

### PR DESCRIPTION
**Pull request by zxh326**
This PR fixes an issue in the multi-namespace cache implementation where repeated calls to the `List()` method on the same list object would accumulate results instead of resetting the list each time. This happens because the current implementation extracts existing items from the provided list object, then appends new items to it, causing the list to grow with each call.

The fix initializes a fresh empty slice for collected items instead of extracting from the existing list object.

fix #3194

### CODE REVIEW

File: pkg/cache/multi_namespace_cache.go [hunk 1]
```diff
@@ -279,10 +279,7 @@ func (c *multiNamespaceCache) List(ctx context.Context, list client.ObjectList,
 		return err
 	}
 
-	allItems, err := apimeta.ExtractList(list)
-	if err != nil {
-		return err
-	}
+	allItems := []runtime.Object{}
```
Comment (alvaroaleman) [inline pkg/cache/multi_namespace_cache.go:282]: While I agree this change makes sense, its a breaking one - Can we mark it as such?

/ok-to-test

Comment (zxh326) [reply pkg/cache/multi_namespace_cache.go:282]: Do you have any suggestions?

Comment (sbueringer) [reply pkg/cache/multi_namespace_cache.go:282]: Sorry for the delay. I changed the PR title that's enough

**Comment by sbueringer** [comment]
@zxh326 If you have time, can you please address this finding: https://github.com/kubernetes-sigs/controller-runtime/pull/3195#discussion_r2084690320

Would be great to get this into the next CR minor :)

File: pkg/cache/multi_namespace_cache.go [hunk 2]
```diff
@@ -279,10 +279,7 @@ func (c *multiNamespaceCache) List(ctx context.Context, list client.ObjectList,
 		return err
 	}
```
[the remark this answers is not in the document]
Comment (zxh326) [reply pkg/cache/multi_namespace_cache.go:280]: done, I changed the code back to the old version for testing, it works.

[the remark this answers is not in the document]
Comment (sbueringer) [reply pkg/cache/multi_namespace_cache.go:280]: Thx!

**Comment by sbueringer** [comment]
Thank you!

/lgtm
/approve
