### PR TITLE
:bug: InformerCache: Do not require leader lease

### LINKED ISSUE #677: Cache-Backed reader only works when the leader lease was acquired
Currently, the cache-backed reader returned from the `Manager` only works when the leader lease was acquired, because otherwise it doesn't get started.

There are cases in which it is useful to have it working even without the leader lease, basically every runnable that itself doesn't require leader election.

### PR DESCRIPTION
**Pull request by alvaroaleman**
This PR makes the `informerCache` implement the `LeaderElectionRunnable` interface to signal that it doesn't need leader election. This is done so other `runnables` that also do not need leader election can use the cache-backed reader.

Fixes #677

### CODE REVIEW

File: pkg/cache/informer_cache.go [hunk 1]
```diff
@@ -140,6 +140,12 @@ func (ip *informerCache) GetInformer(obj runtime.Object) (Informer, error) {
 	return i.Informer, err
 }
 
+// NeedLeaderElection implements the LeaderElectionRunnable interface
```
Comment (alvaroaleman) [inline pkg/cache/informer_cache.go]: Unfortunately we can not verify the interface implementation via a `var _ manager.LeaderElectionRunnable = &informerCache{}` as that would result in an import cycle

File: pkg/cache/informer_cache_test.go [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+var _ = Describe("informerCache", func() {
+	It("should not require LeaderElection", func() {
+		cfg := &rest.Config{}
+
+		mapper, err := apiutil.NewDynamicRESTMapper(cfg, apiutil.WithLazyDiscovery)
+		Expect(err).ToNot(HaveOccurred())
+
+		c, err := cache.New(cfg, cache.Options{Mapper: mapper})
+		Expect(err).ToNot(HaveOccurred())
```
Comment (alvaroaleman) [inline pkg/cache/informer_cache_test.go]: I couldn't find a matcher for "type X implements interface Y", the closes to that I found is `BeAssignableToTypeOf` but that errors out if one of the two is nil.

Comment (DirectXMan12) [reply pkg/cache/informer_cache_test.go]: this is clear enough.  If you're really worried, you can always add an explanation after the "be true" part as a format string, but I think this is readable enough for now.
