### PR TITLE
:bug: Populate GVK for listed objects

### LINKED ISSUE #284: MapObject.Object contains empty GroupVersionKind
I noticed that `MapObject.Object` instances passed to a `handler.ToRequestsFunc` function contains empty `GroupVersionKind`. The code I have looks like the following:

```go
mapFn := handler.ToRequestsFunc(
	func(a handler.MapObject) []reconcile.Request {
		var requests []reconcile.Request
		apps := listApplications(mgr.GetClient(), a.Meta.GetNamespace())
		for _, app := range apps {
			ref := app.Spec.Selector.ObjectRef
			gvk := a.Object.GetObjectKind().GroupVersionKind()
			if gvk.Empty() {
				log.Printf("Empty GVK for object %s/%s", a.Meta.GetNamespace(), a.Meta.GetName())
				return requests
			}
			if ref != nil && ref.Name == a.Meta.GetName() && ref.Kind == gvk.Kind {
				requests = append(requests, reconcile.Request{
					NamespacedName: types.NamespacedName{
						Namespace: app.Namespace,
						Name:      app.Name,
					},
				})
			}
		}
		return requests
	})
``` 

The logs show multiple occurrences of `Empty GVK for object ...`.

### PR DESCRIPTION
**Pull request by JoelSpeed**
Fixes #284. Populates GroupVersionKind for objects returned by the List method.

This supersedes #296. I've rebased the branch, fixed up the conflicts and found an issue where we seemed to not be deepcopying items out of the cache before returning.

I've maintained @liyinan926's ownership of the commits so they should still be credited for their work.

/CC @DirectXMan12

### CODE REVIEW

File: pkg/cache/internal/cache_reader.go [hunk 1]
```diff
@@ -125,7 +125,9 @@ func (c *CacheReader) List(_ context.Context, out runtime.Object, opts ...client
 		if !isObj {
 			return fmt.Errorf("cache contained %T, which is not an Object", obj)
 		}
-		runtimeObjs = append(runtimeObjs, obj)
+		outObj := obj.DeepCopyObject()
```
Comment (shawn-hurley) [inline pkg/cache/internal/cache_reader.go]: I don't believe that we need to deep copy here because these objects are all created from within this function? 

Thoughts?

Comment (JoelSpeed) [reply pkg/cache/internal/cache_reader.go]: I added the `DeepCopy` because it stopped the race detector going off when I was running tests so there must be something funky going on here but I'm not sure what 🤷‍♂️

Comment (shawn-hurley) [reply pkg/cache/internal/cache_reader.go]: 👍 wonder if it is what the indexer gives us for each list is just the cached object? I will look it up to see eventually :) thanks for the explanation!

File: pkg/cache/cache_test.go [hunk 2]
```diff
@@ -198,6 +198,19 @@ func CacheTest(createCacheFunc func(config *rest.Config, opts cache.Options) (ca
...
 				})
 
+				It("should be able to list objects with GVK populated", func() {
+					By("listing pods")
+					out := &kcorev1.PodList{}
+					Expect(informerCache.List(context.Background(), out)).To(Succeed())
+
+					By("verifying that the returned pods have GVK populated")
+					Expect(out.Items).NotTo(BeEmpty())
+					Expect(out.Items).Should(SatisfyAny(HaveLen(3), HaveLen(4)))
```
Comment (shawn-hurley) [inline pkg/cache/cache_test.go]: If we are getting 4 pods, I think that is a bug in the namespaced cache implementation. I will attempt to re-create locally.

I think we may need to file an issue and merge this with a TODO remove `HaveLen(4)` IMO. 

/cc @DirectXMan12

Comment (JoelSpeed) [reply pkg/cache/cache_test.go]: Don't know if you managed to repro locally or not, but to me it looks like the [regular cache](https://github.com/kubernetes-sigs/controller-runtime/blob/7f16f2b744937bb10e5a3acca56aa5b54f534813/pkg/cache/cache_test.go#L76) will be returning [4 pods](https://github.com/kubernetes-sigs/controller-runtime/blob/7f16f2b744937bb10e5a3acca56aa5b54f534813/pkg/cache/cache_test.go#L100-L103) as it lists across all namespaces(?) whereas the [multinamespaced cache](https://github.com/kubernetes-sigs/controller-runtime/blob/7f16f2b744937bb10e5a3acca56aa5b54f534813/pkg/cache/cache_test.go#L79) will only list 3 as there is a [pod in a namespace](https://github.com/kubernetes-sigs/controller-runtime/blob/7f16f2b744937bb10e5a3acca56aa5b54f534813/pkg/cache/cache_test.go#L103) that it isn't caching?

I haven't looked into this thoroughly though so am kinda guessing how the two different caches behave 🤷‍♂️

**Comment by JoelSpeed** [comment]
/assign @pwittrock
Forgot to do the assign that the robot recommended

**Comment by shawn-hurley** [comment]
/lgtm 

@DirectXMan12

File: pkg/cache/internal/cache_reader.go (hunk 1 above)
Comment (DirectXMan12) [reply pkg/cache/internal/cache_reader.go]: I think we should've been deepcopying anyway, since that's what we do elsewhere anyway.
