### PR TITLE
:bug: fix runnable run twice issue

### LINKED ISSUE #478: Runnable added after manager started skips leader election and may run twice
If a runnable is added after the manager has started, the runnable is unconditionally started. In the case that the runnable should wait for leader election, it will start early (without leadership) and then it will be started again when the manager wins election.

https://github.com/kubernetes-sigs/controller-runtime/pull/466#issuecomment-498816582

### PR DESCRIPTION
**Pull request by adohe**
fix #478 @DirectXMan12 @abursavich ptal

### CODE REVIEW

File: pkg/manager/internal.go [hunk 1]
```diff
@@ -347,6 +352,7 @@ func (cm *controllerManager) startLeaderElection() (err error) {
 		RetryPeriod:   cm.retryPeriod,
 		Callbacks: leaderelection.LeaderCallbacks{
 			OnStartedLeading: func(_ context.Context) {
+				cm.isLeader = true
```
Comment (abursavich) [inline pkg/manager/internal.go]: Setting `isLeader` needs to be protected by the mutex. I might suggest moving it into `startLeaderElectionRunnables` and changing its name to something like `startedLeader`?

File: pkg/manager/internal.go [hunk 2]
```diff
@@ -135,14 +136,18 @@ func (cm *controllerManager) Add(r Runnable) error {
...
 	}
 
+	shouldStart := false
+
 	// Add the runnable to the leader election or the non-leaderelection list
 	if leRunnable, ok := r.(LeaderElectionRunnable); ok && !leRunnable.NeedLeaderElection() {
+		shouldStart = cm.started
 		cm.nonLeaderElectionRunnables = append(cm.nonLeaderElectionRunnables, r)
 	} else {
+		shouldStart = cm.started && (cm.isLeader || cm.resourceLock == nil)
```
Comment (abursavich) [inline pkg/manager/internal.go]: If you push take the suggestion from the other comment, this could be simplified to `shouldStart = cm.startedLeader`.

File: pkg/manager/internal.go (hunk 1 above)
Comment (adohe) [reply pkg/manager/internal.go]: yeap, that makes more sense. 👍

**Comment by DirectXMan12** [comment]
fyi #444

**Comment by abursavich** [comment]
The code looks good to me, but it would be nice to see the tests pass -- but that failure doesn't look like your fault.

**Comment by adohe** [comment]
@DirectXMan12 kind ping~

**Comment by adohe** [comment]
@mengqiy @DirectXMan12 the CI is happy, kind ping~
