### PR TITLE
:sparkles: Clean-up installed CRDs on Stop()

### LINKED ISSUE #420: envtest.Environment should cleanup CRDs on Stop()
`envtest.Environment` does not cleanup CRDs when `Stop()` is called. When you use an `Environment` with `UseExistingCluster = true`, this leaves CRDs hanging around in the cluster. So the second time you run `go test`, it will fail because "can't create CRDs which already exist". So it would be really useful if `Stop()` also deleted the CRDs by default irrespective of whether we use existing cluster or not.

### PR DESCRIPTION
**Pull request by pires**
But only if `USE_EXISTING_CLUSTER` is set to `true` as there's no point in doing it if the control-plane is going away.

Fixes #420

### CODE REVIEW

**Comment by pires** [comment]
Maybe you can take a look at this one, @alvaroaleman? Please!

File: pkg/envtest/server.go [hunk 1]
```diff
@@ -135,10 +135,10 @@ type Environment struct {
 }
 
 // Stop stops a running server.
-// If USE_EXISTING_CLUSTER is set to true, this method is a no-op.
+// If USE_EXISTING_CLUSTER is set to true, uninstall whatever CRDs were installed with Start().
 func (te *Environment) Stop() error {
 	if te.useExistingCluster() {
-		return nil
+		return UninstallCRDs(te.Config, te.CRDInstallOptions)
```
Comment (alvaroaleman) [inline pkg/envtest/server.go]: I don't think we should be doing this by default because:

* This may be unexpected for users that re-use an existing cluster they have workloads on that use the given CRD they care
* This breaks parallel tests that use the same cluster

Maybe make this an opt-in option of the `Environment`?

File: pkg/envtest/crd.go [hunk 2]
```diff
@@ -180,6 +181,32 @@ func (p *poller) poll() (done bool, err error) {
...
+	// Create each CRD
+	for _, crd := range options.CRDs {
+		log.V(1).Info("uninstalling CRD", "crd", crd.Name)
+		if err := cs.ApiextensionsV1beta1().CustomResourceDefinitions().Delete(crd.Name, &metav1.DeleteOptions{}); err != nil {
+			return err
+		}
+	}
+	return nil
+
+	return nil
```
Comment (alvaroaleman) [inline pkg/envtest/crd.go]: I believe one `return nil` is sufficient here :)

File: pkg/envtest/envtest_test.go [hunk 3]
```diff
@@ -216,4 +216,105 @@ var _ = Describe("Test", func() {
...
+								Served:  true,
+							},
+						}},
+				},
+			},
+				CRDInstallOptions{MaxTime: 50 * time.Millisecond, PollInterval: 15 * time.Millisecond},
+			)
+			Expect(err).NotTo(HaveOccurred())
+
+			err = UninstallCRDs(env.Config, CRDInstallOptions{
```
Comment (alvaroaleman) [inline pkg/envtest/envtest_test.go]: Apart from the functionality itself, maybe also test when its being executed, i.E. probably not by default?

File: pkg/envtest/crd.go (hunk 2 above)
Comment (pires) [reply pkg/envtest/crd.go]: 🤦‍♂ will fix.

File: pkg/envtest/envtest_test.go (hunk 3 above)
Comment (pires) [reply pkg/envtest/envtest_test.go]: Indeed! Will do.

File: pkg/envtest/server.go (hunk 1 above)
Comment (pires) [reply pkg/envtest/server.go]: This makes total sense! I'm _ashamed_ it didn't cross my mind. Will do.

File: pkg/envtest/envtest_test.go (hunk 3 above)
Comment (pires) [reply pkg/envtest/envtest_test.go]: Actually, I just realized this test will only pass if `USE_EXISTING_CLUSTER` is `true` - which was the only scenario I actually tested against. So I realize now that uninstalling only when the aforementioned environment variable is used was a stupid pre-optimization that I am removing now.

Comment (pires) [reply pkg/envtest/envtest_test.go]: I also just realized the existing tests do not cover starting/stopping the environment but only installing CRDs by explicitly call `InstallCRDs`, so I'm unsure how to proceed here. Thoughts?

**Comment by gerred** [comment]
After the fixes, this looks good! Thanks @pires 

/lgtm

File: pkg/envtest/envtest_test.go (hunk 3 above)
Comment (gerred) [reply pkg/envtest/envtest_test.go]: Might be beyond the scope of this PR imo, maybe we have external e2e tests that do this? In KUDO we're working on abstracting out `kudo test` into [kuttl](https://github.com/kudobuilder/kuttl) which can start external environments with kind.

**Comment by gerred** [comment]
looks like the teardown code is removing the CRDs as well which is why that test is failing? so uninstallCRDs runs but the suite harness is trying to do the same thing.

/lgtm cancel

PR itself looks ok pending fixing that test. :)

**Comment by pires** [comment]
Well, I can re-install the CRDs so the `AfterEach` is happy or I can add a validation to said func that tries to delete only if CRD is present. I'll go with the latter for now and change later if you're not pleased with that solution.

**Comment by gerred** [comment]
Latter sounds good :+1: thanks @pires!

**Comment by pires** [comment]
Sorry for the few force-pushes but stupid me was working from a different machine that didn't had my latest changes and that took me a while to figure out 🤦‍♂

File: pkg/envtest/envtest_test.go (hunk 3 above)
Comment (pires) [reply pkg/envtest/envtest_test.go]: I'd say it's beyond the scope of this PR.

File: pkg/envtest/envtest_test.go [hunk 4]
```diff
@@ -216,4 +227,105 @@ var _ = Describe("Test", func() {
...
+				Paths: []string{filepath.Join(".", "testdata")},
+			})
+			Expect(err).NotTo(HaveOccurred())
```
Comment (alvaroaleman) [inline pkg/envtest/envtest_test.go]: I think we should also test if they are actually gone, not just if we didn't return an error :P

Comment (pires) [reply pkg/envtest/envtest_test.go]: Agreed.

Comment (pires) [reply pkg/envtest/envtest_test.go]: Done.

Comment (pires) [reply pkg/envtest/envtest_test.go]: Done.

File: pkg/envtest/envtest_test.go [hunk 5]
```diff
@@ -216,4 +227,126 @@ var _ = Describe("Test", func() {
...
+				"bazs.qux.example.com",
+				"captains.crew.example.com",
+				"firstmates.crew.example.com",
+				"drivers.crew.example.com",
+			}
+			placeholder := &v1beta1.CustomResourceDefinition{}
+			Eventually(func() bool {
+				for _, crd := range crds {
+					err = c.Get(context.TODO(), types.NamespacedName{Name: crd}, placeholder)
+					notFound := err != nil && apierrors.IsNotFound(err)
```
Comment (alvaroaleman) [inline pkg/envtest/envtest_test.go]: Nit: AFAIK you don't need to nilcheck the errors before passing it into apierrors.IsNotFound

File: pkg/envtest/server.go [hunk 6]
```diff
@@ -135,8 +135,15 @@ type Environment struct {
...
 
 // Stop stops a running server.
-// If USE_EXISTING_CLUSTER is set to true, this method is a no-op.
+// Previously installed CRDs, as listed in CRDInstallOptions.CRDs, will be uninstalled
+// if CRDInstallOptions.CleanUpAfterUse are set to true.
 func (te *Environment) Stop() error {
+	if te.CRDInstallOptions.CleanUpAfterUse {
+		if err := UninstallCRDs(te.Config, te.CRDInstallOptions); err != nil {
+			// This error should be harmless so just log it.
+			log.Error(err, "failed to uninstall CRDs")
```
Comment (alvaroaleman) [inline pkg/envtest/server.go]: IMHO the decision if this error should be handled or not belongs to the caller, hence we should return it

File: pkg/envtest/envtest_test.go (hunk 5 above)
Comment (pires) [reply pkg/envtest/envtest_test.go]: Maybe I'm misunderstanding what the code does but there's no check for `nil` in https://github.com/kubernetes/apimachinery/blob/master/pkg/api/errors/errors.go#L485-L488, so my understanding is if I pass `nil`, I'll get a panic.

File: pkg/envtest/server.go (hunk 6 above)
Comment (pires) [reply pkg/envtest/server.go]: Done.

File: pkg/envtest/envtest_test.go (hunk 5 above)
Comment (alvaroaleman) [reply pkg/envtest/envtest_test.go]: Its a bit buried, underneath it uses https://github.com/kubernetes/apimachinery/blob/adc6f4cd9e7d28fc1c1e5efc658d940d55c0f356/pkg/api/errors/errors.go#L642 which does a type assertion which doesn't match on nil, so a default is returned that is not a `NotFound` so you'll just get back a `false` and no panic. But again, just a nit.

Comment (pires) [reply pkg/envtest/envtest_test.go]: TIL, thanks!

But if it's a nit, I ask you approve this as is as it will make the code easier to read for newbies like myself.

**Comment by DirectXMan12** [comment]
/approve

thanks!
