### PR TITLE
:bug: Ensure that webhook server is thread/start-safe

### LINKED ISSUE #1148: Intermittent yet consistent `nil pointer` issue in /webhook/admission/http.go:84
We got a webhook error intermittently but consistently, about 1 out of 7 deploys. The webhook error we got is:
```
Error from server (InternalError): Internal error occurred: failed calling webhook "namespaces.hnc.x-k8s.io": Post https://hnc-webhook-service.hnc-system.svc:443/validate-v1-namespace?timeout=30s: stream error: stream ID 13; INTERNAL_ERROR
```

Here's what the log says (the 8th line specifically):
```
2020-09-01T14:54:21.716198833Z stderr F 2020/09/01 14:54:21 http2: panic serving 10.244.0.1:48384: runtime error: invalid memory address or nil pointer dereference
2020-09-01T14:54:21.716224783Z stderr F goroutine 232 [running]:
2020-09-01T14:54:21.716228967Z stderr F net/http.(*http2serverConn).runHandler.func1(0xc000f4e020, 0xc00075ff8e, 0xc0006ae900)
2020-09-01T14:54:21.716232Z stderr F    /usr/local/go/src/net/http/h2_bundle.go:5713 +0x16b
2020-09-01T14:54:21.716234692Z stderr F panic(0x1791fa0, 0x29da610)
2020-09-01T14:54:21.716237649Z stderr F         /usr/local/go/src/runtime/panic.go:969 +0x166
2020-09-01T14:54:21.716239964Z stderr F sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc000ed9680, 0x7fbd452c1b18, 0xc000cedd80, 0xc00047e500)
2020-09-01T14:54:21.716242278Z stderr F         /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go:84 +0x8a8
2020-09-01T14:54:21.716244784Z stderr F github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1(0x7fbd452c1b18, 0xc000cedd80, 0xc00047e500)
2020-09-01T14:54:21.716247116Z stderr F         /workspace/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:40 +0xab
2020-09-01T14:54:21.716249307Z stderr F net/http.HandlerFunc.ServeHTTP(0xc000ed98c0, 0x7fbd452c1b18, 0xc000cedd80, 0xc00047e500)
2020-09-01T14:54:21.716251671Z stderr F         /usr/local/go/src/net/http/server.go:2012 +0x44
2020-09-01T14:54:21.716253875Z stderr F github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0x1cf9fc0, 0xc000f4e020, 0xc00047e500)
2020-09-01T14:54:21.716256032Z stderr F         /workspace/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:100 +0xda
2020-09-01T14:54:21.716258434Z stderr F net/http.HandlerFunc.ServeHTTP(0xc000ed9a10, 0x1cf9fc0, 0xc000f4e020, 0xc00047e500)
2020-09-01T14:54:21.716260762Z stderr F         /usr/local/go/src/net/http/server.go:2012 +0x44
2020-09-01T14:54:21.716272844Z stderr F github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2(0x1cf9fc0, 0xc000f4e020, 0xc00047e500)
2020-09-01T14:54:21.716275213Z stderr F         /workspace/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:76 +0xb2
2020-09-01T14:54:21.716278353Z stderr F net/http.HandlerFunc.ServeHTTP(0xc000ed9b00, 0x1cf9fc0, 0xc000f4e020, 0xc00047e500)
2020-09-01T14:54:21.716281725Z stderr F         /usr/local/go/src/net/http/server.go:2012 +0x44
2020-09-01T14:54:21.716285187Z stderr F net/http.(*ServeMux).ServeHTTP(0xc000613900, 0x1cf9fc0, 0xc000f4e020, 0xc00047e500)
2020-09-01T14:54:21.716288628Z stderr F         /usr/local/go/src/net/http/server.go:2387 +0x1a5
2020-09-01T14:54:21.71629225Z stderr F net/http.serverHandler.ServeHTTP(0xc000d620e0, 0x1cf9fc0, 0xc000f4e020, 0xc00047e500)
2020-09-01T14:54:21.716294532Z stderr F         /usr/local/go/src/net/http/server.go:2807 +0xa3
2020-09-01T14:54:21.716296648Z stderr F net/http.initALPNRequest.ServeHTTP(0x1cfe640, 0xc000f00090, 0xc000b22a80, 0xc000d620e0, 0x1cf9fc0, 0xc000f4e020, 0xc00047e500)
2020-09-01T14:54:21.71629879Z stderr F  /usr/local/go/src/net/http/server.go:3381 +0x8d
2020-09-01T14:54:21.716300936Z stderr F net/http.(*http2serverConn).runHandler(0xc0006ae900, 0xc000f4e020, 0xc00047e500, 0xc000634220)
2020-09-01T14:54:21.716303197Z stderr F         /usr/local/go/src/net/http/h2_bundle.go:5720 +0x8b
2020-09-01T14:54:21.716305467Z stderr F created by net/http.(*http2serverConn).processHeaders
2020-09-01T14:54:21.716307634Z stderr F         /usr/local/go/src/net/http/h2_bundle.go:5454 +0x4e1
```
The line `/webhook/admission/http.go:84` is
```
wh.log.V(1).Info("received request", "UID", req.UID, "kind", req.Kind, "resource", req.Resource)
```
Since we have `controller-runtime` in the `/vendor` directory, I tried
1) putting `wh.log.Info("xxx")` at the top of the `func (wh *Webhook) ServeHTTP()`. When the intermittent webhook error happened, the logs pointed to that first log line.
2) omitting the `wh.log`s, the intermittent webhook error logs pointed to `reviewResponse = wh.Handle(r.Context(), req)`.

So I guess there's a race-condition that could cause `wh` to be nil? To provide more info, we have some validating webhooks and CRD conversion webhooks.

Also I noticed there a TODO in the code that I'm not sure if it's relevant:
```
	// TODO: add panic-recovery for Handle
	reviewResponse = wh.Handle(r.Context(), req)
	wh.writeResponse(w, reviewResponse)
```

### PR DESCRIPTION
**Pull request by DirectXMan12**
This ensures that the webhook server is both threadsafe & "start-safe"
-- i.e. you can register webhooks after starting the server.  While this
is generally not a common pattern, be allow runnables to be added to the
manager after start, so it makes sense to do the same with hooks & the
server.

Fixes #1148 

/kind bug

### CODE REVIEW

**Comment by adrianludwin** [comment]
Hi, it looks like our workaround to this problem was unsuccessful. Do you have any idea when this might make it into the next release of controller-runtime?

Thanks, A

**Comment by DirectXMan12** [comment]
Hmm... looks like there's a theoretical race in event broadcaster shutdown due to the event broadcaster calling `broadcaster.Action` in a goroutine, potentially leading to a send on a closed channel.  I filed an issue, but I don't think this is caused by this PR.  Upstream issue is https://github.com/kubernetes/kubernetes/issues/94906

File: pkg/manager/internal.go [hunk 1]
```diff
@@ -353,17 +353,32 @@ func (cm *controllerManager) GetAPIReader() client.Reader {
...
+	// Add has its own lock, so just do this separately -- there shouldn't
+	// be a "race" in this lock gap because the condition is the population
+	// of cm.webhookServer, not anything to do with Add.
+	if wasNew {
+		if err := cm.Add(server); err != nil {
+			panic("unable to add webhook server to the controller manager")
 		}
 	}
-	return cm.webhookServer
+	return server
```
Comment (vincepri) [inline pkg/manager/internal.go:381]: Unless I missed something, we should be able to simplify this method. Why do we need an inner function that's called right away?

File: pkg/webhook/server.go [hunk 2]
```diff
@@ -76,6 +76,9 @@ type Server struct {
 
 	// defaultingOnce ensures that the default fields are only ever set once.
 	defaultingOnce sync.Once
+
+	// mu protects access to the webhook map & setFields for Start, Register, etc
+	mu sync.Mutex
```
Comment (vincepri) [inline pkg/webhook/server.go:81]: Nit: Define a mutex above the "protected" fields, so code becomes documentation

File: pkg/manager/internal.go (hunk 1 above)
Comment (DirectXMan12) [reply pkg/manager/internal.go:381]: The IIFE sets the scope for the defer unlock call, which would otherwise be weird to unlock due to multiple return paths.
