### PR TITLE
:sparkles: ErrorIfCRDPathMissing on Environment

### LINKED ISSUE #481: envtest.Environment.Start() silently fails for missing CRD paths
There is no way to specify `envtest.CRDInstallOptions.ErrorIfPathMissing = true` when calling `envtest.Environment.Start()`. As a result, silent failure in the case of missing CRD directories is the default and only behavior when using `.Start()`.

Workaround:

Call `envtest.InstallCRDs()` directly:

```go
	t.Start()
	// ...
	if _, err := envtest.InstallCRDs(t.Config, envtest.CRDInstallOptions{
		Paths: []string{
			filepath.Join("..", "..", "..", "config", "crds"),
			filepath.Join("..", "..", "..", "third_party", "crds"),
		},
		ErrorIfPathMissing: true,
	}); err != nil {
```

### PR DESCRIPTION
**Pull request by knabben**
This PR overwrites the ErrorIfPathMissing from CRDInstallOptions via Environment.ErrorIfCRDPathMissing on Start() method.

Similar to PR #511 but propagates the flag and test the Start() with invalid directories.

Closes #481.

### CODE REVIEW

File: pkg/envtest/envtest_test.go [hunk 1]
```diff
@@ -349,4 +354,20 @@ var _ = Describe("Test", func() {
 			close(done)
 		}, 30)
 	})
+
+	Describe("Start", func() {
+		It("should raise an error", func(done Done) {
```
Comment (alvaroaleman) [inline pkg/envtest/envtest_test.go]: Nit: Elaborate in the name why it should (not) raise an error, i.E. "should raise an error on invalid dir`
