### PR TITLE
🐛 Handle unstructured status update with fake client

### LINKED ISSUE #2493: Panic in fake client when updating status with Unstructured resource
There is a regression in 0.16.2 in the fake client when attempting to update a resource's status with an unstructured object.

In this case, the GVK has a type registered in the scheme, but the client is invoked using an unstructured object. The initial object was also defined as unstructured and [converted to the typed resource inside the tracker](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.16.2/pkg/client/fake/client.go#L292).

The panic is triggered at
https://github.com/kubernetes-sigs/controller-runtime/blob/v0.16.2/pkg/client/fake/client.go#L407

- `obj` is the unstructured value passed to `client.Status().Update()`
- `oldObject` is a typed value managed by the tracker

The two types are incompatible and cannot be reflectively assigned, at least not naively.

```
panic: reflect.Set: value of type v1.MyResource is not assignable to type unstructured.Unstructured [recovered]
	panic: reflect.Set: value of type v1.MyResource is not assignable to type unstructured.Unstructured

goroutine 12 [running]:
testing.tRunner.func1.2({0x105d91e20, 0x140004cc010})
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/testing/testing.go:1545 +0x370
testing.tRunner.func1()
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/testing/testing.go:1548 +0x528
panic({0x105d91e20?, 0x140004cc010?})
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/panic.go:920 +0x254
reflect.Value.assignTo({0x105f00420, 0x14000100900, 0x199}, {0x105b0d7e6, 0xb}, 0x105e6d040, 0x0)
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/reflect/value.go:3307 +0x340
reflect.Value.Set({0x105e6d040, 0x14000683588, 0x199}, {0x105f00420, 0x14000100900, 0x199})
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/reflect/value.go:2260 +0xa8
sigs.k8s.io/controller-runtime/pkg/client/fake.versionedTracker.update({{0x1060581a0, 0x140000a0370}, 0x140002885b0, 0x1400007fe30}, {{0x1400069dde0, 0x1a}, {0x1400069ddfb, 0x2}, {0x140001ae220, 0xd}}, ...)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/client/fake/client.go:407 +0x938
sigs.k8s.io/controller-runtime/pkg/client/fake.(*fakeClient).update(0x140000a03c0, {0x10605dd18, 0x14000683588}, 0x1, {0x14000356dc0, 0x1, 0x1})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/client/fake/client.go:789 +0x46c
sigs.k8s.io/controller-runtime/pkg/client/fake.(*fakeSubResourceClient).Update(0x14000516f18, {0x106054c50, 0x14000024c30}, {0x10605dd18, 0x14000683588}, {0x0, 0x0, 0x0})
```

### PR DESCRIPTION
**Pull request by scothis**
In order to prevent unintentional mutations outside of the status during a status update, the non-status fields are copied back onto the passed object.

This operation now gracefully handles both unstructured and typed objects. Previously, it would panic if an unstructured object was passed for a GVK known to the scheme, as internally the object within the tracker is converted to the typed equivalent. The two types cannot be directly assigned to each other and instead must be copied.

Adds a failing test to demonstrate the bug, and the fix to make the test pass.

Resolves #2493

### CODE REVIEW

**Comment by scothis** [comment]
/retest

looks like a test flake

**Comment by troy0820** [comment]
/retest 

Did this not get retriggered? Looks like a golangci-lint error. Interesting.

**Comment by scothis** [comment]
> Did this not get retriggered?

It did. the first run's flake was a timeout in the leader election code.

**Comment by troy0820** [comment]
/assign @alvaroaleman 

Assigning @alvaroaleman  as he made the initial change.  I'd look to him to give the lgtm. But this looks good to me. 

Thanks for the contribution @scothis

File: pkg/client/fake/client.go [hunk 1]
```diff
@@ -972,6 +974,19 @@ func copyStatusFrom(old, new runtime.Object) error {
 	return nil
 }
 
+// copyFrom copies from old into new
+func copyFrom(old, new runtime.Object) error {
+	oldMapStringAny, err := toMapStringAny(old)
```
Comment (alvaroaleman) [inline pkg/client/fake/client.go:979]: The original reason for not doing this anymore is that it might leave stale data in the target. I am confused as to why this isn't a problem anymore. Maybe we just didn't add sufficient test coverage?

Comment (scothis) [reply pkg/client/fake/client.go:979]: This isn't changing existing behavior. No tests were modified or removed. What it does is handle a mix of  types and unstructured objects gracefully, instead of panicing.

What stale data is left behind?

Comment (troy0820) [reply pkg/client/fake/client.go:979]: What @alvaroaleman is referring to I believe is that before this function was added, we removed a function similar to this where we were doing a `copyFrom` because of the issues with that function leaving stale data around. 
https://github.com/kubernetes-sigs/controller-runtime/pull/2479

https://github.com/kubernetes-sigs/controller-runtime/pull/2479#discussion_r1320627434

If this being added doesn't impact what is already there (covers previous tests and your new test case) and handles the new case to fix the regression, the new test coverage should be sufficient to have this fix be in and resolve the issue with unstructured stuff.  

I believe we have unstructured.Unstructured tests cases and if not being caught in testing, it begs the question how did those tests pass, if this problem still presented itself. 

_IANAM, (I am not a maintainer)_

Comment (scothis) [reply pkg/client/fake/client.go:979]: the previous tests and code handled both `typed->typed` and `unstructured->unstructured`, but triggered a panic with `typed->unstructured`. The mix can happen when the GVK is registered in the scheme, so the resource in the tracker is always converted to the typed form, and then the user performs a status update using an unstructured object.

It's a bit esoteric as most users will favor a typed resource when available, but we hit it.

Comment (alvaroaleman) [reply pkg/client/fake/client.go:979]: Ah, we also added code to [zero the target](https://github.com/kubernetes-sigs/controller-runtime/blob/6860cfb3d210ac028dc5d744e7824a99c8841f07/pkg/client/fake/client.go#L1015), that is why it works. Thanks for the patch and sorry for the review delay

File: pkg/client/fake/client_test.go [hunk 2]
```diff
@@ -1677,6 +1677,52 @@ var _ = Describe("Fake client", func() {
...
+		Expect(err).NotTo(HaveOccurred())
+		cl := NewClientBuilder().WithStatusSubresource(obj).WithObjects(obj).Build()
+
+		err = unstructured.SetNestedField(obj.Object, "Never", "spec", "restartPolicy")
+		Expect(err).NotTo(HaveOccurred())
+		err = unstructured.SetNestedField(obj.Object, "Running", "status", "phase")
+		Expect(err).NotTo(HaveOccurred())
+
+		Expect(cl.Update(context.Background(), obj)).To(Succeed())
+		Expect(cl.Get(context.Background(), client.ObjectKeyFromObject(obj), obj)).To(Succeed())
```
Comment (alvaroaleman) [inline pkg/client/fake/client_test.go:1697]: Would you actually mind to do the retrieval and verification using `corev1.Pod` instead of `unstructured.Unstructured`? That I believe would simplify the code a bit but more importantly clarify the intention of the testcase. I had to read the title three times to understand it and that is with the context from the PR. Same for the other testcase.

Comment (scothis) [reply pkg/client/fake/client_test.go]: Updated the tests. Sorry for the delay, I was traveling last week.

**Review by alvaroaleman — APPROVED** [review]
thanks!
