### PR TITLE
:bug: add error check when no apiType is provided for reconciliation

### LINKED ISSUE #1181: Builder causes panics when For isn't called
Currently the causes builder panics when `For` isn't called, because it constructs a `Kind` source with a nil `Type` field.  We should detect this in the builder's `doWatch` method and return an actual error instead.

/kind bug
/priority important-longterm
/good-first-issue

### PR DESCRIPTION
**Pull request by prafull01**
When no reconciliation type is provided in the For(...) function to the Builder, it used to panic. Added the error handling if no apiType is provided in the For(...) function.

Fixes #1181

### CODE REVIEW

File: pkg/builder/controller.go [hunk 1]
```diff
@@ -167,6 +167,10 @@ func (blder *Builder) Build(r reconcile.Reconciler) (controller.Controller, erro
 	if blder.forInput.err != nil {
 		return nil, blder.forInput.err
 	}
+	// Checking the reconcile type exist or not
+	if blder.forInput.object == nil {
+		return nil, fmt.Errorf("must provide an object for reconciliation")
```
Comment (alvaroaleman) [inline pkg/builder/controller.go:172]: please use `errors.New` for error messages without a format string

Comment (prafull01) [reply pkg/builder/controller.go:172]: @alvaroaleman In the same func, fmt.Errorf is used for other errors which do not have a format string. IMHO this needs to be fixed horizontally for all such error messages.

**Review by alvaroaleman — APPROVED** [review]
/lgtm
/approve
