### PR TITLE
:sparkles: update CRD if already present

### LINKED ISSUE #342: Envtest is not idempotent when installing CRDs, an issue when UseExistingCluster=true
We want to use envtest against an existing cluster and are having issues when installing CRDs. Envtest will fail on the second running of the tests because the CRDs already exist in the cluster.  This is only an issue when using an existing cluster because normally envtest starts a new control plane each time. 

Example setup we want to use:
```
		testEnv = &envtest.Environment{
			CRDDirectoryPaths:  []string{filepath.Join("..", "config", "crds")},
			UseExistingCluster: true,
		}
```

And error we get:
```  
Expected error:
      <*errors.StatusError | 0xc00012a2d0>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {SelfLink: "", ResourceVersion: "", Continue: ""},
              Status: "Failure",
              Message: "customresourcedefinitions.apiextensions.k8s.io \"mycrd.meep.io\" already exists",
              Reason: "AlreadyExists",
              Details: {
                  Name: "mycrd.meep.io",
                  Group: "apiextensions.k8s.io",
                  Kind: "customresourcedefinitions",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 409,
          },
      }
      customresourcedefinitions.apiextensions.k8s.io "mycrd.meep.io" already exists
  not to have occurred
```

Is it possible to have envtest reinstall CRDs on every run rather than fail?

Thanks
Ed & @samze & @ablease

### PR DESCRIPTION
**Pull request by pires**
In testenv, update the CRD if it's already present on the cluster instead of failing to continue.

Fixes #342
Closes #457

### CODE REVIEW

File: pkg/envtest/crd.go [hunk 1]
```diff
@@ -190,8 +192,17 @@ func CreateCRDs(config *rest.Config, crds []*apiextensionsv1beta1.CustomResource
 	// Create each CRD
 	for _, crd := range crds {
 		log.V(1).Info("installing CRD", "crd", crd.Name)
-		if _, err := cs.ApiextensionsV1beta1().CustomResourceDefinitions().Create(crd); err != nil {
-			return err
+		var err error
+		if _, err = cs.ApiextensionsV1beta1().CustomResourceDefinitions().Get(crd.Name, metav1.GetOptions{}); err != nil {
+			if apierrors.IsNotFound(err) {
```
Comment (alvaroaleman) [inline pkg/envtest/crd.go]: Could we have a test for the "IsAlreadyExists" case succeeding? Other than that lgtm, thanks!
/ok-to-test

Comment (pires) [reply pkg/envtest/crd.go]: On it. Thanks for taking the time to review.

Comment (pires) [reply pkg/envtest/crd.go]: I ended up adding a re-install step and validation to the existing _install CRDs_ test. Does that suffice?

**Comment by DirectXMan12** [comment]
add a log line to this warning about it (and switch the title to say "update CRD if already present" to make it more likely that people'll notice it in the release notes), then I think we're good here.

I think it'd be fine even without, but better to provide feedback than give someone a debugging headache.

**Comment by pires** [comment]
Done, PTAL.

**Comment by DirectXMan12** [comment]
did the test change disappear?  I seem to recall that there was a change to the existing test here before...

otherwise lgtm

**Comment by pires** [comment]
Rebased `master` onto this branch and added a couple tests. I think there were no tests before, sorry for that.

**Comment by pires** [comment]
I have a question, though. Why is `WaitForCRDs` explicitly called in tests that call `InstallCRDs`, when the latter func already calls the former?

**Comment by pires** [comment]
As is tradition around here, I forgot to include two new files and that's why I force-pushed. Need caffeine.

**Comment by DirectXMan12** [comment]
> As is tradition around here, I forgot to include two new files and that's why I force-pushed. Need caffeine.

heh, definitely had those days.  Need a lint that checks if we've had caffeine yet for the day :-P

As for the test, did some poking around, and found the failure.  It's another caffeine error :-P  Commented inline.

File: pkg/envtest/crd.go [hunk 2]
```diff
@@ -225,8 +225,18 @@ func CreateCRDs(config *rest.Config, crds []*apiextensionsv1beta1.CustomResource
...
+				_, err = cs.ApiextensionsV1beta1().CustomResourceDefinitions().Create(crd)
+			}
+			if apierrors.IsAlreadyExists(err) {
+				log.V(1).Info("CRD already exists, updating", "crd", crd.Name)
+				_, err = cs.ApiextensionsV1beta1().CustomResourceDefinitions().Update(crd)
+			}
+			if err != nil {
+				return err
+			}
```
Comment (DirectXMan12) [inline pkg/envtest/crd.go]: You also want some logic outside the get check, otherwise if `err == nil` (it already exists), we'll never update.

In fact, this is probably better as a `Create` check here still.

Comment (DirectXMan12) [reply pkg/envtest/crd.go]: we also need to load the resource version to do the update -- apparently we can't do an unconditional update here.

File: pkg/envtest/envtest_test.go [hunk 3]
```diff
@@ -226,8 +226,228 @@ var _ = Describe("Test", func() {
...
+		Expect(err).NotTo(HaveOccurred())
+
+		// Expect to find updated CRD
+
+		crd = &v1beta1.CustomResourceDefinition{}
+		err = c.Get(context.TODO(), types.NamespacedName{Name: "drivers.crew.example.com"}, crd)
+		Expect(err).NotTo(HaveOccurred())
+		Expect(crd.Spec.Names.Kind).To(Equal("Driver"))
+		Expect(len(crd.Spec.Versions)).To(BeEquivalentTo(3))
+		Expect(crd.ResourceVersion).NotTo(BeEquivalentTo(firstRV))
```
Comment (DirectXMan12) [inline pkg/envtest/envtest_test.go]: you'll also need a `close(done)` at the end here, or just remove the done argument and the timeout

Comment (pires) [reply pkg/envtest/envtest_test.go]: thank you for putting me out of my misery 🙇

File: pkg/envtest/crd.go (hunk 2 above)
Comment (pires) [reply pkg/envtest/crd.go]: I really needed caffeine when working on this. I am very sorry for that. Clearly, a conflict would never be the result of a GET 🤦‍♂
Now, I didn't know we'd forcibly need to set the resourceVersion when updating so TIL. THANKS!

**Comment by pires** [comment]
Are we good @DirectXMan12?

File: pkg/envtest/crd.go [hunk 4]
```diff
@@ -225,8 +225,18 @@ func CreateCRDs(config *rest.Config, crds []*apiextensionsv1beta1.CustomResource
...
 	for _, crd := range crds {
 		log.V(1).Info("installing CRD", "crd", crd.Name)
-		if _, err := cs.ApiextensionsV1beta1().CustomResourceDefinitions().Create(crd); err != nil {
-			return err
+		if existingCrd, err := cs.ApiextensionsV1beta1().CustomResourceDefinitions().Get(crd.Name, metav1.GetOptions{}); err != nil {
+			if apierrors.IsNotFound(err) {
+				if _, err := cs.ApiextensionsV1beta1().CustomResourceDefinitions().Create(crd); err != nil {
+					return err
+				}
+			}
```
Comment (DirectXMan12) [inline pkg/envtest/crd.go]: should we have a `return err` here?

Comment (DirectXMan12) [reply pkg/envtest/crd.go]: i.e. `if there was an error fetching the existing CRD, and the error wasn't not found, treat it as an error`

Comment (pires) [reply pkg/envtest/crd.go]: You're right. Fixing.

Comment (pires) [reply pkg/envtest/crd.go]: Done.

**Comment by gerred** [comment]
/assign @directxman12

looks like everything has been addressed - I reviewed the code and nothing else stands out. thanks @pires

**Comment by DirectXMan12** [comment]
Added a bit more of a PR description -- in general, I prefer to see a bit of a description beyond the bugs it fixes and the title, even if it's relatively minimal.

otherwise looks good :-)

/lgtm
/approve

**Comment by DirectXMan12** [comment]
Also, since this is a bit of a behavioral change, I've made it a feature instead of a bugfix, just to play it safe
