### PR TITLE
🐛 Fix informer cache creating pointers to pointers 

### LINKED ISSUE #656: Unable to List Objects with pointer slices
I've been working on a controller that interacts with another project's CRDs. All was going well until I encountered an error when trying to list owned objects using the reconciler's client with the code below:
```goland
if err := r.List(ctx, &ownedRules, client.MatchingField(ruleOwnerKey, req.Name)); err != nil {
	log.Error(err, "unable to list owned rules")
	return ctrl.Result{}, err
}
```

This caused the following error: 
```
2019-10-23T12:41:43.568+0100    ERROR   controller-runtime.controller   Reconciler error        {"controller": "servicelevelobjective", "request": "default/energy-fastly", "error": "cannot get cache for *v1.PrometheusRuleList, its element **v1.PrometheusRule is not a runtime.Object"}
```

Looking over the definition of the `PrometheusRuleList` CRD I noted that the element type for the `Items` field is `*PrometheusRule`.
https://github.com/coreos/prometheus-operator/blob/v0.33.0/pkg/apis/monitoring/v1/types.go#L679

It appears the code in `controller-runtime/pkg/cache/informer_cache.go` tries to determine whether the items can be cast to `runtime.Object` and in the process assumes that the slice's elements are not pointers.

https://github.com/kubernetes-sigs/controller-runtime/blob/v0.2.2/pkg/cache/informer_cache.go#L84-L85
```golang
elemType := reflect.Indirect(reflect.ValueOf(itemsPtr)).Type().Elem()
cacheTypeValue := reflect.Zero(reflect.PtrTo(elemType))
```

I've fixed this locally by adding a check before converting the elemType to a Ptr which seems sufficient to fix the error in my use case.
```golang
elemType := reflect.Indirect(reflect.ValueOf(itemsPtr)).Type().Elem()
if elemType.Kind() != reflect.Ptr {
	elemType = reflect.PtrTo(elemType)
}

cacheTypeValue := reflect.Zero(elemType)
```

I'm happy to put together a PR with this fix in it but wanted to raise the issue for discussion first in case there may be knock-on effects that I've not yet encountered as I haven't done extensive testing on my end yet.

Any thoughts from the owners on this one?

### PR DESCRIPTION
**Pull request by alvaroaleman**
Makes the cache cope with list types that have a slice of pointers as `Items` field.

Fixes #656
Supersedes and thereby closes #667

### CODE REVIEW

File: pkg/controller/controller_suite_test.go [hunk 1]
```diff
@@ -62,3 +76,51 @@ var _ = AfterSuite(func() {
...
+
+// UnconventionalListType is used to test CRDs with List types that
+// have a slice of pointers rather than a slice of literals.
+type UnconventionalListType struct {
+	metav1.TypeMeta   `json:",inline"`
+	metav1.ObjectMeta `json:"metadata,omitempty"`
+	Spec              string `json:"spec,omitempty"`
+}
+
+// DeepCopyObject implements runtime.Object
```
Comment (alvaroaleman) [inline pkg/controller/controller_suite_test.go]: I handwrote these mostly because I was too lazy to figure out how to plug deepcopy-gen into a  hackscript and have it verified by CI. Also it may not be able to cope with a folder that contains multiple packages (`controller` and `controller_test`). Since the correctness of the DeepCopies is not really relevant for the test, thats IMHO good enough

**Comment by DewaldV** [comment]
Awesome job on the test @alvaroaleman I got about 50% of the way there when I attempted it last year but had brought a lot more code along so this looks much cleaner than my test implementation. :smile:

**Comment by alvaroaleman** [comment]
> Awesome job on the test @alvaroaleman! I got about 50% of the way there when I attempted it last year but had brought a lot more code along so this looks much cleaner than my test implementation. smile


Yeah it actually turned out to be a lot more involved than anticipated, initially I thought I could directly test the `informerCache` but that isn't really possible as it embedds a `*InformersMap`, so mocking that would require some more refactorings. So I ended up just writing an integration test :upside_down_face:

**Comment by alvaroaleman** [comment]
@vincepri Mind having a look?

File: pkg/controller/controller_suite_test.go (hunk 1 above)
Comment (vincepri) [reply pkg/controller/controller_suite_test.go]: Can you add a comment with the above? :)

File: pkg/cache/informer_cache.go [hunk 2]
```diff
@@ -93,7 +93,11 @@ func (ip *informerCache) List(ctx context.Context, out runtime.Object, opts ...c
 		}
 		// http://knowyourmeme.com/memes/this-is-fine
 		elemType := reflect.Indirect(reflect.ValueOf(itemsPtr)).Type().Elem()
```
Comment (vincepri) [inline pkg/cache/informer_cache.go]: For posterity, can we also add a comment here explaining what we're trying to do and why? I checked out the code and understood we're pretty much trying to figure out the type of the list passed in, but that might be a lot to ask for folks not familiar with the codebase.

Let's also move the logic to a local function and add some unit tests for it.

Comment (alvaroaleman) [reply pkg/cache/informer_cache.go]: Done, PTAL. I had to move the `UnconventionalListType` into a different package, because its now used by both unit and integration tests and would otherwise have caused an import cycle.
