### PR TITLE
:warning: Remove defaulting for leader election ID

### LINKED ISSUE #445: Remove defaulting for leader election ID
Currently, the leader election ID defaults to `controller-leader-election-helper`.  Since it is convenient to not configure anything for the leader election ID, it will crash whenever two controller-runtime based controllers run in the same namespace or have the same namespace configured for the leader election (e.G. `kube-system`).

This is especially bad since there is no logging about the lock being held by a different controller, so from a users perspective this looks like the controller just froze.

### PR DESCRIPTION
**Pull request by alvaroaleman**
With the current defaulting for the leader election ID, there is a clash
as soon as two controller that do not have it explicitly configured run
in the same namespace or have the same namespace configured for leader
election.

This is especially bad since there is no logging about the lock being
held by a different controller, so from a users perspective this looks
like the controller just froze.

Fixes #445

/assign @DirectXMan12 
/cc @JoelSpeed

### CODE REVIEW

**Comment by DirectXMan12** [comment]
/hold

till we resolve the discussion on #445 (I'm happy to be corrected on that issue, just want to finish up that discussion first)

**Comment by DirectXMan12** [comment]
I don't think we meant to close this...

**Comment by alvaroaleman** [comment]
@DirectXMan12 re https://github.com/kubernetes-sigs/controller-runtime/issues/445#issuecomment-561860554: Can we add this change to the `breaking-next` milestone?

**Comment by DirectXMan12** [comment]
Added.  I think we've got a breaking one coming up due to #749, which I think we need in for supportability reasons.

**Comment by shawn-hurley** [comment]
@DirectXMan12 bump to get this in as #749 merged

File: pkg/manager/manager_test.go [hunk 1]
```diff
@@ -143,15 +143,16 @@ var _ = Describe("manger.Manager", func() {
 				m, err := New(cfg, Options{
 					LeaderElection:          true,
 					LeaderElectionNamespace: "default",
+					LeaderElectionID:        "test-leader-election-id",
```
Comment (DirectXMan12) [inline pkg/manager/manager_test.go]: lol, this test should have a different name now.  I'll fix it elsewhere.
