### PR TITLE
🐛 remove deprecated workqueue metrics with invalid names

### LINKED ISSUE #436: Queue metrics broken when using the controller builder
When starting a controller the following messages get logged:
```
E0518 20:13:50.847341   12082 client_go_adapter.go:318] descriptor Desc{fqName: "node-application_depth", help: "Current depth of workqueue: node-application", constLabels: {}, variableLabels: []} is invalid: "node-application_depth" is not a valid metric name
E0518 20:13:50.847688   12082 client_go_adapter.go:328] descriptor Desc{fqName: "node-application_adds", help: "Total number of adds handled by workqueue: node-application", constLabels: {}, variableLabels: []} is invalid: "node-application_adds" is not a valid metric name
E0518 20:13:50.848958   12082 client_go_adapter.go:339] descriptor Desc{fqName: "node-application_queue_latency", help: "How long an item stays in workqueuenode-application before being requested.", constLabels: {}, variableLabels: []} is invalid: "node-application_queue_latency" is not a valid metric name
E0518 20:13:50.849992   12082 client_go_adapter.go:350] descriptor Desc{fqName: "node-application_work_duration", help: "How long processing an item from workqueuenode-application takes.", constLabels: {}, variableLabels: []} is invalid: "node-application_work_duration" is not a valid metric name
E0518 20:13:50.851079   12082 client_go_adapter.go:363] descriptor Desc{fqName: "node-application_unfinished_work_seconds", help: "How many seconds of work node-application has done that is in progress and hasn't been observed by work_duration. Large values indicate stuck threads. One can deduce the number of stuck threads by observing the rate at which this increases.", constLabels: {}, variableLabels: []} is invalid: "node-application_unfinished_work_seconds" is not a valid metric name
E0518 20:13:50.852133   12082 client_go_adapter.go:374] descriptor Desc{fqName: "node-application_longest_running_processor_microseconds", help: "How many microseconds has the longest running processor for node-application been running.", constLabels: {}, variableLabels: []} is invalid: "node-application_longest_running_processor_microseconds" is not a valid metric name
E0518 20:13:50.853298   12082 client_go_adapter.go:384] descriptor Desc{fqName: "node-application_retries", help: "Total number of retries handled by workqueue: node-application", constLabels: {}, variableLabels: []} is invalid: "node-application_retries" is not a valid metric name
```

Used controller-runtime version: 
```toml
[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.2.0-beta.1"
```

Code:
```golang
	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{})
	if err != nil {
		log.Fatal("Unable to start manager", zap.Error(err))
	}

	err = ctrl.NewControllerManagedBy(mgr).
		For(&corev1.Node{}).
		Owns(&corev1.ConfigMap{}).
		Complete(&controller.Reconciler{
			Client: mgr.GetClient(),
			Log:    log.Named("some_controller"),
		})
	if err != nil {
		log.Fatal("Unable to add some_controller", zap.Error(err))
	}

	log.Info("starting manager")
	if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {
		log.Fatal("problem running manager", zap.Error(err))
	}
```

The problematic code: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/builder/build.go#L234
```golang
func (blder *Builder) getControllerName() (string, error) {
	gvk, err := getGvk(blder.apiType, blder.mgr.GetScheme())
	if err != nil {
		return "", err
	}
	name := fmt.Sprintf("%s-application", strings.ToLower(gvk.Kind))
	return name, nil
}
```

This leads to invalid metric names like `node-application_depth`.

Potential solutions IMHO:
- Remove the `-application` suffix
- Add a `Named(name string)` function to the builder so controllers can have more meaningful names

WDYT?

### PR DESCRIPTION
**Pull request by abursavich**
Migration work was already done to move controller-runtime from k8s v1.13 to v1.14, however this introduced certain issues.

Unfortunately, workqueue_queue_duration_seconds and workqueue_work_duration_seconds were included in v0.1.10, but were recorded with microsecond values. Moving to k8s v1.14 corrects those values to seconds.

Primarily this change removes the metrics that were deprecated in k8s v1.14, but were never previously included in v0.1 of controller-runtime and thereby fixes #436.

The one metric that was deprecated and retained is longest_running_processor_microseconds, as it was included in v0.1.10.

### CODE REVIEW

File: pkg/metrics/workqueue.go [hunk 1]
```diff
@@ -0,0 +1,193 @@
...
+func (workqueueMetricsProvider) NewDepthMetric(name string) workqueue.GaugeMetric {
+	const metricName = "depth"
+	depth := prometheus.NewGauge(prometheus.GaugeOpts{
+		Subsystem:   workQueueSubsystem,
+		Name:        metricName,
+		Help:        "Current depth of workqueue",
+		ConstLabels: prometheus.Labels{"name": name},
+	})
+	if err := Registry.Register(depth); err != nil {
+		log.Error(err, "failed to register "+metricName+" metric", "name", name)
```
Comment (DirectXMan12) [inline pkg/metrics/workqueue.go]: error messages should never be variable -- that's what the key-value pairs are for

Comment (abursavich) [reply pkg/metrics/workqueue.go]: i'm happy to change them if you'd like, but the messages are actually constant expressions (`metricName` is a local constant in each of the methods)

**Comment by abursavich** [comment]
Thanks for the review, @DirectXMan12. PTAL.

**Comment by abursavich** [comment]
The test failure was fixed with https://github.com/kubernetes-sigs/controller-runtime/pull/466 ... I'll push again to retrigger Travis.

**Comment by abursavich** [comment]
After rebasing and picking up https://github.com/kubernetes-sigs/controller-runtime/commit/17e09762d0468e410e184ab726eb673b4a919868, Github *really* doesn't want me to push https://github.com/kubernetes-sigs/controller-runtime/blob/master/.github/main.workflow to my repo.

**Comment by abursavich** [comment]
I cherrypicked the race fix without the Github Action change, but, uhhh... I don't know how to get around this Github issue. If this PR goes through, I might try deleting my repo and re-forking post-Action commit.

**Comment by DirectXMan12** [comment]
That's a bizarre message.  Are you not using a normal git client?  Keep me updated on that issue -- if it's causing you issues, it might cause others issues, so we may need to figure out a way around it or back it out.

**Comment by DirectXMan12** [comment]
It let me push it.  I've rebased up to master, so this should work now.  Will merge once tests pass.
