### PR TITLE
🐛 Fix panic for lazy dynamicRESTMapper

### LINKED ISSUE #1712: Panic from dynamicRESTMapper when using lazy initialization
When `dynamicRESTMapper` lazy initialization fails, any subsequent calls to it will panic (`runtime error: invalid memory address or nil pointer dereference`) because `staticMapper` is uninitialized.

I ran into this when my cluster could not be reached, so I'll illustrate the problem this way, but any error returned by `setStaticMapper` will result in the same issue.

## How to reproduce
```golang
import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/client/apiutil"
	"sigs.k8s.io/controller-runtime/pkg/client/config"
)

func main() {
	// get a client config; this should succeed
	cfg := config.GetConfigOrDie()
	// to simulate a refused connection, set cfg.Host to some URL that won't answer
	cfg.Host = "https://127.0.0.1:12345"
	// create a new dynamicRESTMapper instance with lazy initialization; this should succeed
	mapper, _ := apiutil.NewDynamicRESTMapper(cfg, apiutil.WithLazyDiscovery)
	// call any method on mapper; this should result in an error
	_, err := mapper.KindFor(schema.GroupVersionResource{Group: "", Version: "v1", Resource: "pods"})
	if err != nil {
		fmt.Println("failed to get kind for pods")
	}
	// later on, (or from another place/goroutine in your code) call any method on mapper; this should panic
	_, err := mapper.KindFor(schema.GroupVersionResource{Group: "", Version: "v1", Resource: "pods"})
	if err != nil {
		fmt.Println("failed to get kind for pods")
	}
}
```

## Suggested fix
`sync.Once` is not suitable for guarding the lazy initialization code because the initialization should be retried until successful, not just tried once. I couldn't find an existing solution, so I propose to create a custom version of `sync.Once` that is _done_ only when the function given to `Do` returns with `true`, although, other alternative implementations might be fine too.

```golang
type Once struct {
	done uint32
	m    Mutex
}

func (o *Once) Do(f func() bool) {
	if atomic.LoadUint32(&o.done) == 0 {
		o.doSlow(f)
	}
}

func (o *Once) doSlow(f func() bool) {
	o.m.Lock()
	defer o.m.Unlock()
	if o.done == 0 {
		if f() {
			atomic.StoreUint32(&o.done, 1)
		}
	}
}
```
This should be used instead of `sync.Once`, updating the inline function passed to `Do` with a `return err == nil` statement.

### PR DESCRIPTION
**Pull request by FillZpp**
Signed-off-by: FillZpp <FillZpp.pub@gmail.com>

Fix panic for lazy dynamicRESTMapper to make `setStaticMapper` successfully once, which means if dynamicRESTMapper fails to `setStaticMapper`, it will do it once again in next `init`.

fixes #1712

### CODE REVIEW

File: pkg/client/apiutil/dynamicrestmapper_test.go [hunk 1]
```diff
@@ -146,11 +145,28 @@ var _ = Describe("Dynamic REST Mapper", func() {
...
 
-	PIt("should lazily initialize if the lazy option is used", func() {
-
-	})
+		It("should lazily initialize if the lazy option is used", func() {
+			var err error
+			var failedOnce bool
+			mockErr := fmt.Errorf("mock failed once")
+			mapper, err = NewDynamicRESTMapper(cfg, WithLazyDiscovery, WithCustomMapper(func() (meta.RESTMapper, error) {
+				// Make newMapper failed once
```
Comment (siliconbrain) [inline pkg/client/apiutil/dynamicrestmapper_test.go:154]:
```suggestion
				// Make newMapper fail once
```

**Review by siliconbrain — APPROVED** [review]
lgtm, thanks @FillZpp!

File: pkg/client/apiutil/dynamicrestmapper_test.go (hunk 1 above)
Comment (FillZpp) [reply pkg/client/apiutil/dynamicrestmapper_test.go]: Done, thanks.

**Review by alvaroaleman — APPROVED** [review]
